name: Excute Scoring Runner

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Example: run every day at midnight UTC
    
  # This allows manual triggers for the workflow
  workflow_dispatch:  # Enables manual trigger
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure requirements.txt is updated

    - name: Set Google Service Account Secrets as Environment Variables
      run: |
        echo "GOOGLE_TYPE=${{ secrets.GOOGLE_TYPE }}" >> $GITHUB_ENV
        echo "GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }}" >> $GITHUB_ENV
        echo "GOOGLE_PRIVATE_KEY_ID=${{ secrets.GOOGLE_PRIVATE_KEY_ID }}" >> $GITHUB_ENV
        echo "GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_EMAIL=${{ secrets.GOOGLE_CLIENT_EMAIL }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "GOOGLE_AUTH_URI=${{ secrets.GOOGLE_AUTH_URI }}" >> $GITHUB_ENV
        echo "GOOGLE_TOKEN_URI=${{ secrets.GOOGLE_TOKEN_URI }}" >> $GITHUB_ENV
        echo "GOOGLE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.GOOGLE_AUTH_PROVIDER_X509_CERT_URL }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_X509_CERT_URL=${{ secrets.GOOGLE_CLIENT_X509_CERT_URL }}" >> $GITHUB_ENV
        echo "GOOGLE_UNIVERSE_DOMAIN=${{ secrets.GOOGLE_UNIVERSE_DOMAIN }}" >> $GITHUB_ENV

    - name: Run the Python script
      run: |
        python main.py
